In [18]:
import json
import pandas as pd
filename = "../data/Cubic_0_Website.json"

data = json.load(open(filename))


def parse_data(data):
    df = pd.DataFrame([
        {
            "time_relative": float(pkt["_source"]["layers"]["frame"]["frame.time_relative"]),
            "window_size": float(pkt["_source"]["layers"]["tcp"].get("tcp.window_size_value", 0)),
            # Handle cases where "tcp.analysis" might not exist
            "acks_frame": float(pkt["_source"]["layers"]["tcp"].get("tcp.analysis", {}).get("tcp.analysis.acks_frame", 0)),
            "ack_rtt": float(pkt["_source"]["layers"]["tcp"].get("tcp.analysis", {}).get("tcp.analysis.ack_rtt", 0)),
            "initial_rtt": float(pkt["_source"]["layers"]["tcp"].get("tcp.analysis", {}).get("tcp.analysis.initial_rtt", 0)),
            "bytes_in_flight": float(pkt["_source"]["layers"]["tcp"].get("tcp.analysis", {}).get("tcp.analysis.bytes_in_flight", 0)),
            "push_bytes_sent": float(pkt["_source"]["layers"]["tcp"].get("tcp.analysis", {}).get("tcp.analysis.push_bytes_sent", 0)),
        }
        for pkt in data
    ])
    return df



df = parse_data(data)
df

,time_relative,window_size,acks_frame,ack_rtt,initial_rtt,bytes_in_flight,push_bytes_sent
0,0.000000,62727.0,0.0,0.000000,0.000000,0.0,0.0
1,0.020612,62643.0,1.0,0.020612,0.000000,0.0,0.0
2,0.040706,491.0,2.0,0.020094,0.040706,0.0,0.0
3,0.040837,491.0,0.0,0.000000,0.040706,163.0,163.0
4,0.061346,489.0,4.0,0.020509,0.040706,0.0,0.0
5,0.061704,489.0,0.0,0.000000,0.040706,2896.0,2896.0
6,0.061753,489.0,0.0,0.000000,0.040706,5792.0,2896.0
7,0.061753,489.0,0.0,0.000000,0.040706,8688.0,2896.0
8,0.061753,489.0,0.0,0.000000,0.040706,11584.0,2896.0
9,0.061753,489.0,0.0,0.000000,0.040706,13032.0,1448.0
10,0.061774,489.0,0.0,0.000000,0.040706,14480.0,2896.0
11,0.081779,469.0,6.0,0.020075,0.040706,0.0,0.0
12,0.081790,447.0,7.0,0.020037,0.040706,0.0,0.0
13,0.081791,425.0,8.0,0.020038,0.040706,0.0,0.0
14,0.081797,403.0,9.0,0.020044,0.040706,0.0,0.0
15,0.081799,392.0,10.0,0.020046,0.040706,0.0,0.0
16,0.081800,381.0,11.0,0.020026,0.040706,0.0,0.0
17,0.102395,489.0,0.0,0.000000,0.040706,2896.0,2896.0
18,0.102396,489.0,0.0,0.000000,0.040706,5792.0,2896.0
19,0.102396,489.0,0.0,0.000000,0.040706,5976.0,184.0
20,0.122470,359.0,18.0,0.020075,0.040706,0.0,0.0
21,0.122481,337.0,19.0,0.020085,0.040706,0.0,0.0
22,0.122482,336.0,20.0,0.020086,0.040706,0.0,0.0
23,0.123080,336.0,0.0,0.000000,0.000000,0.0,0.0
24,0.143708,489.0,24.0,0.020628,0.040706,0.0,0.0
25,0.163815,336.0,25.0,0.020107,0.040706,0.0,0.0